
# Add missing common names
ch.station$Common[ch.station$Scientific == "Ambrosia psylotachya"] <- "Cuman ragweed"
ch.station$Common[ch.station$Scientific == "Ambrosia psilotacleria - annual or weak perennial?"] <- "Cuman ragweed"
ch.station$Common[ch.station$Scientific == "Baccharis seritnroides"] <- "Desert broom"
ch.station$Common[ch.station$Scientific == "Boerhaavia coullcal"] <- "Coulter's spiderling"
ch.station$Common[ch.station$Scientific == "Bracilis aril"] <- "Blue grama"
ch.station$Common[ch.station$Scientific == "Bothriochloa barbinodis"] <- "Cane beardgrass"
ch.station$Common[ch.station$Scientific == "Chlor. Virginia"] <- "Feather fingergrass"
ch.station$Common[ch.station$Scientific == "Eragostis cilianersis"] <- "Stinkgrass"
ch.station$Common[ch.station$Scientific == "Eragostis curvula"] <- "Boer lovegrass"
ch.station$Common[ch.station$Scientific == "Euphorbia"] <- "Spurge"
ch.station$Common[ch.station$Scientific == "Lorla writghtii"] <- "Lorla wrightii (?)"
ch.station$Common[ch.station$Scientific == "Mach pin"] <- "Mach pin (?)"
ch.station$Common[ch.station$Scientific == "Melinis repens"] <- "Rose Natal grass"
ch.station$Common[ch.station$Scientific == "Mullugo"] <- "Carpetweed"
ch.station$Common[ch.station$Scientific == "Port. unb"] <- "Purslane"
ch.station$Common[ch.station$Scientific == "Portuliea"] <- "Purslane"
ch.station$Common[ch.station$Scientific == "Sida neomexicanum"] <- "New Mexico fanpetals"

# Correct common names based on scientific name
ch.station$Common[ch.station$Scientific == "bouteloua barbata?"] <- "Sixweek grama"
ch.station$Common[ch.station$Scientific == "Eriogonum"] <- "Annual buckwheat"
ch.station$Common[ch.station$Scientific == "Eriogonum fasciculatum"] <- "Eastern Mojave buckwheat"
ch.station$Common[ch.station$Scientific == "Eriogonum polycladon"] <- "Sorrel buckwheat"
ch.station$Common[ch.station$Scientific == "Eriogonum wrightii"] <- "Bastardsage"

# Standardize common names
ch.station$Common[ch.station$Common == "Annual grama 2021"] <- "Sixweek grama"
ch.station$Common[ch.station$Common == "Annual Forbs"] <- "Annual forb (year summed)"
ch.station$Common[ch.station$Common == "Annual Grass"] <- "Annual grass (year summed)"
ch.station$Common[ch.station$Common == "annual lovegrass"] <- "Annual lovegrass"
ch.station$Common[ch.station$Common == "annual panic"] <- "Annual panic"
ch.station$Common[ch.station$Common == "Annual panic grass"] <- "Annual panic"
ch.station$Common[ch.station$Common == "AZ Wrightwort"] <- "AZ wrightwort"
ch.station$Common[ch.station$Common == "Arizona Wrightwort"] <- "AZ wrightwort"
ch.station$Common[ch.station$Common == "Arizona wrightwort"] <- "AZ wrightwort"
ch.station$Common[ch.station$Common == "Barn yard"] <- "Barnyard"
ch.station$Common[ch.station$Common == "Barnyard grama"] <- "Barnyard"
ch.station$Common[ch.station$Common == "Bedstraw"] <- "Bracted bedstraw"
ch.station$Common[ch.station$Common == "Bideus"] <- "Bidens"
ch.station$Common[ch.station$Common == "Brickle bush"] <- "Brickellia"
ch.station$Common[ch.station$Common == "brown panic"] <- "Brown panic"
ch.station$Common[ch.station$Common == "Buckwheat/desert trumpet"] <- "Buckwheat"
ch.station$Common[ch.station$Common == "buckwheat trumpetflower"] <- "Buckwheat"
ch.station$Common[ch.station$Common == "Buckwheat/Trumpetflower"] <- "Buckwheat"
ch.station$Common[ch.station$Common == "Cane bluestem"] <- "Cane beardgrass"
ch.station$Common[ch.station$Common == "cholla"] <- "Cholla"
ch.station$Common[ch.station$Common == "Coulter wrinklefruit"] <- "Coulter's wrinklefruit"
ch.station$Common[ch.station$Common == "Coulters wrinklefruit"] <- "Coulter's wrinklefruit"
ch.station$Common[ch.station$Common == "cupgrass"] <- "Cupgrass"
ch.station$Common[ch.station$Common == "Cup grass"] <- "Cupgrass"
ch.station$Common[ch.station$Common == "Desert zinia"] <- "Desert zinnia"
ch.station$Common[ch.station$Common == "Dracherea"] <- "Dracherea (?)"
ch.station$Common[ch.station$Common == "Euphorbia"] <- "Spurge"
ch.station$Common[ch.station$Common == "Feather five-finger"] <- "Feather fingergrass" 
ch.station$Common[ch.station$Common == "feather fingergrass"] <- "Feather fingergrass" 
ch.station$Common[ch.station$Common == "Indianwheat"] <- "Indian wheat"
ch.station$Common[ch.station$Common == "lambsquarters"] <- "Lambsquarters"
ch.station$Common[ch.station$Common == "Matweed/Carpet weed"] <- "Carpetweed"
ch.station$Common[ch.station$Common == "Pepper weed"] <- "Pepperweed"
ch.station$Common[ch.station$Common == "Panic grass"] <- "Annual panic"
ch.station$Common[ch.station$Common == "Rock hybiscus"] <- "Rock hibiscus"
ch.station$Common[ch.station$Common == "Rothrock Grama"] <- "Rothrock grama"
ch.station$Common[ch.station$Common == "sixweek grama"] <- "Sixweek grama"
ch.station$Common[ch.station$Common == "snake cotton"] <- "Snakecotton"
ch.station$Common[ch.station$Common == "Seniorita Threeawn"] <- "Senorita threeawn"
ch.station$Common[ch.station$Common == "spiderling"] <- "Coulter's spiderling"
ch.station$Common[ch.station$Common == "Spiderling"] <- "Coulter's spiderling"
ch.station$Common[ch.station$Common == "sorrel buckwheat"] <- "Sorrel buckwheat"
ch.station$Common[ch.station$Common == "Tansey mustard"] <- "Tansymustard"
ch.station$Common[ch.station$Common == "Trumpetflower"] <- "Buckwheat"
ch.station$Common[ch.station$Common == "trumpetflower"] <- "Buckwheat"
ch.station$Common[ch.station$Common == "Unknown aster"] <- "Annual aster"
ch.station$Common[ch.station$Common == "Unknown cholla"] <- "Cholla"
ch.station$Common[ch.station$Common == "Unknown cholla 2021"] <- "Cholla"

# Assign missing scientific names (when known) and correct spelling
ch.station$Scientific[ch.station$Common == "African lovegrass"] <- "Eragrostis echinochloidea"
ch.station$Scientific[ch.station$Common == "Annual panic"] <- "Panicum"
ch.station$Scientific[ch.station$Common == "Barnyard"] <- "Echinochloa"
ch.station$Scientific[ch.station$Common == "Bidens"] <- "Bidens"
ch.station$Scientific[ch.station$Common == "Brittlebush"] <- "Encelia farinosa"
ch.station$Scientific[ch.station$Common == "Brown panic"] <- "Panicum"
ch.station$Scientific[ch.station$Common == "Buckwheat"] <- "Eriogonum inflatum"
ch.station$Scientific[ch.station$Common == "Cholla"] <- "Cylindropuntia"
ch.station$Scientific[ch.station$Common == "Cane beardgrass"] <- "Bothriochloa barbinodis"
ch.station$Scientific[ch.station$Common == "Carpetweed"] <- "Mollugo verticillata"
ch.station$Scientific[ch.station$Common == "Coulter's spiderling"] <- "Boerhavia coulteri"
ch.station$Scientific[ch.station$Common == "Feather fingergrass"] <- "Chloris virgata"
ch.station$Scientific[ch.station$Common == "Matweed"] <- "Guilleminea"
ch.station$Scientific[ch.station$Common == "Pepperweed"] <- "Lepidium"
ch.station$Scientific[ch.station$Common == "Prickly pear"] <- "Opuntia"
ch.station$Scientific[ch.station$Common == "Rock hibiscus"] <- "Hibiscus denudatus"
ch.station$Scientific[ch.station$Common == "Snakecotton"] <- "Froelichia"
ch.station$Scientific[ch.station$Common == "Senorita threeawn"] <- "Aristida"
ch.station$Scientific[ch.station$Common == "Shrubby buckwheat"] <- "Eriogonum" # C19 10+98
ch.station$Scientific[ch.station$Common == "Sixweek grama"] <- "Bouteloua barbata"
ch.station$Scientific[ch.station$Common == "Spurge"] <- "Euphorbia"
ch.station$Scientific[ch.station$Common == "Tansymustard"] <- "Descurainia pinnata"
ch.station$Scientific[ch.station$Common == "Witch grass"] <- "Panicum"
ch.station$Scientific[ch.station$Scientific == "Amaranthus palmeri/fimbriatus?"] <- "Amaranthus palmeri/fimbriatus"
ch.station$Scientific[ch.station$Scientific == "Ambrosia confertifolia"] <- "Ambrosia confertiflora"
ch.station$Scientific[ch.station$Scientific == "Ambrosia psylotachya"] <- "Ambrosia psilostachya"
ch.station$Scientific[ch.station$Scientific == "Baccharis sarothrae"] <- "Baccharis sarothroides"
ch.station$Scientific[ch.station$Scientific == "Bociharia"] <- "Boerhavia"
ch.station$Scientific[ch.station$Scientific == "Boerharia"] <- "Boerhavia"
ch.station$Scientific[ch.station$Scientific == "Boerhaavia coullcal"] <- "Boerhavia coulteri"
ch.station$Scientific[ch.station$Scientific == "Bouteloua barbarta"] <- "Bouteloua barbata"
ch.station$Scientific[ch.station$Scientific == "bouteloua barbata?"] <- "Bouteloua barbata"
ch.station$Scientific[ch.station$Scientific == "Bouteloua chondrosoides"] <- "Bouteloua chondrosioides"
ch.station$Scientific[ch.station$Scientific == "Bouteloua rothrochii"] <- "Bouteloua rothrockii"
ch.station$Scientific[ch.station$Scientific == "Bracilis aril"] <- "Bouteloua gracilis"
ch.station$Scientific[ch.station$Scientific == "Carlowrightii"] <- "Carlowrightia arizonica"
ch.station$Scientific[ch.station$Scientific == "Carlo wrightiii"] <- "Carlowrightia arizonica"
ch.station$Scientific[ch.station$Scientific == "Carlowrightii arizonica"] <- "Carlowrightia arizonica"
ch.station$Scientific[ch.station$Scientific == "Chlor. Virginia"] <- "Chloris virgata"
ch.station$Scientific[ch.station$Scientific == "Chloris vigata"] <- "Chloris virgata"
ch.station$Scientific[ch.station$Scientific == "chenopodcezemisc"] <- NA
ch.station$Scientific[ch.station$Scientific == "Dentata Brichellia, maybe Aguitia"] <- "Brickellia dentata?"
ch.station$Scientific[ch.station$Scientific == "Echinchloa"] <- "Echinochloa"
ch.station$Scientific[ch.station$Scientific == "Echinechloa"] <- "Echinochloa"
ch.station$Scientific[ch.station$Scientific == "Echonocereus"] <- "Echinocereus"
ch.station$Scientific[ch.station$Scientific == "Eragostis cilianersis"] <- "Eragrostis cilianensis"
ch.station$Scientific[ch.station$Scientific == "Eragrostis echinocloidea"] <- "Eragrostis echinochloidea"
ch.station$Scientific[ch.station$Scientific == "Eriochloa acumintata"] <- "Eriochloa acuminata"
ch.station$Scientific[ch.station$Scientific == "Ferocactus wizliseni"] <- "Ferocactus wislizenii"
ch.station$Scientific[ch.station$Scientific == "Galiuum microphyllum"] <- "Galium microphyllum"
ch.station$Scientific[ch.station$Scientific == "Gutierrezia sarothra"] <- "Gutierrezia sarothrae"
ch.station$Scientific[ch.station$Scientific == "Mullugo"] <- "Mollugo sp."
ch.station$Scientific[ch.station$Scientific == "Mullugo sp."] <- "Mollugo sp."
ch.station$Scientific[ch.station$Scientific == "Mullugo vert."] <- "Mollugo verticillata"
ch.station$Scientific[ch.station$Scientific == "panicum sp."] <- "Panicum" 
ch.station$Scientific[ch.station$Scientific == "Physallas"] <- "Physalis" 
ch.station$Scientific[ch.station$Scientific == "Port. unb"] <- "Portulaca"
ch.station$Scientific[ch.station$Scientific == "Portuliea"] <- "Portulaca"
ch.station$Scientific[ch.station$Scientific == "Sida neomexicanum"] <- "Sida neomexicana"
ch.station$Scientific[ch.station$Scientific == "Tilinum"] <- "Talinum"
ch.station$Scientific[ch.station$Scientific == "Zinia pumila"] <- "Zinnia acerosa"
